# netlify.toml

[[edge_functions]]
  path = "/api/shorten"
  function = "shortener"

[[edge_functions]]
  path = "/s/*"
  function = "shortener"
  
[[edge_functions]]
  path = "/rest-v1/*"
  function = "services"

[[redirects]]
  from = "/api/molscribe/*"
  to = "https://yujieq-molscribe.hf.space/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200